USE Master

GO

DROP DATABASE DomsBlog

GO

CREATE DATABASE DomsBlog

GO

USE DomsBlog

GO

CREATE TABLE BlogTypes
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	Name			NVARCHAR(32)	NOT NULL	UNIQUE,

	PRIMARY KEY(Id)
)

GO

CREATE TABLE Blogs
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	BlogTypeId		INT				NOT NULL,
	ShortTitle		NVARCHAR(32)	NOT NULL,
	Title			NVARCHAR(128)	NOT NULL,
	Abstract		NVARCHAR(512)	NOT NULL,
	PostedDate		DATETIME		NOT NULL	DEFAULT GETUTCDATE(),
	IsVisible		BIT				NOT NULL,

	PRIMARY KEY(Id),

	FOREIGN KEY(BlogTypeId) REFERENCES BlogTypes(Id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)

GO

CREATE TABLE BlogPages
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	BlogId			INT				NOT NULL,
	PageName		NVARCHAR(32)	NOT NULL,
	PageNumber		INT				NOT NULL,
	TextContent		NVARCHAR(MAX)	NOT NULL,

	PRIMARY KEY(Id),

	FOREIGN KEY(BlogId) REFERENCES Blogs(Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)

CREATE TABLE Images
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	BlogId			INT				NULL,
	FileName		VARCHAR(32)		NOT NULL	UNIQUE,
	Caption			NVARCHAR(80)	NOT NULL,
	AltText			NVARCHAR(80)	NULL,

	PRIMARY KEY(Id),

	FOREIGN KEY(BlogId) REFERENCES Blogs(Id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
)

GO

CREATE TABLE Tags
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	TagName			NVARCHAR(20)	NOT NULL,

	PRIMARY KEY(Id)
)

GO

CREATE TABLE TaggedBlogs
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	TagId			INT				NOT NULL,
	BlogId			INT				NOT NULL,

	PRIMARY KEY(Id),

	FOREIGN KEY(TagId) REFERENCES Tags(Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	FOREIGN KEY(BlogId) REFERENCES Blogs(Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)

GO

CREATE TABLE BlogComments
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	BlogId			INT				NOT NULL,
	ParentCommentId	INT				NULL,
	Title			NVARCHAR(64)	NOT NULL,
	TextContent		NVARCHAR(4000)	NOT NULL,
	Author			NVARCHAR(64)	NULL,
	EmailAddress	VARCHAR(128)	NULL,
	Website			VARCHAR(256)	NULL,
	IPAddress		VARCHAR(64)		NOT NULL,
	IsAdminComment	BIT				NOT NULL	DEFAULT 0,
	PostedDate		DATETIME		NOT NULL	DEFAULT GETUTCDATE(),
	Approved		Bit				NOT NULL	DEFAULT 0,
	ApprovalKey		VARCHAR(50)		NULL,

	PRIMARY KEY(Id),

	FOREIGN KEY(BlogId) REFERENCES Blogs(Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	FOREIGN KEY(ParentCommentId) REFERENCES BlogComments(Id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)

GO

CREATE TABLE Polls
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	Question		NVARCHAR(256)	NOT NULL,
	PostedDate		DATETIME		NOT NULL	DEFAULT GETUTCDATE(),
	
	PRIMARY KEY(Id)
)

GO

CREATE TABLE PollOptions
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	PollId			INT				NOT NULL,
	Answer			NVARCHAR(256)	NOT NULL,
	Votes			INT				NOT NULL	DEFAULT 0,
	OrderIndex		INT				NOT NULL,
	SuggestComment	BIT				NOT NULL	DEFAULT 0,

	PRIMARY KEY(Id),

	FOREIGN KEY(PollId) REFERENCES Polls(Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)

GO

CREATE TABLE PollComments
(
	Id				INT				NOT NULL	IDENTITY(1,1),
	PollId			INT				NOT NULL,
	ParentCommentId	INT				NULL,
	Title			NVARCHAR(32)	NOT NULL,
	TextContent		NVARCHAR(2000)	NOT NULL,
	Author			NVARCHAR(64)	NULL,
	EmailAddress	VARCHAR(128)	NOT NULL,
	Website			VARCHAR(256)	NULL,
	Location		NVARCHAR(128)	NULL,
	IPAddress		VARCHAR(64)		NOT NULL,
	IsAdminComment	BIT				NOT NULL	DEFAULT 0,
	PostedDate		DATETIME		NOT NULL	DEFAULT GETUTCDATE(),

	PRIMARY KEY(Id),

	FOREIGN KEY(PollId) REFERENCES Polls(Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	FOREIGN KEY(ParentCommentId) REFERENCES PollComments(Id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)

GO