<%@ Page Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage" %>

<asp:Content ID="headerTitle" ContentPlaceHolderID="TitleContent" runat="server">
    Legal Stuff &amp; Acknowledgements
</asp:Content>

<asp:Content ID="metaContent" ContentPlaceHolderID="MetaContent" runat="server">
    <meta name="description" content="Terms &amp; Conditions of this website, including acknowledgements." />
</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <ul class="Breadcrumbs">
        <li><a href="/About">About</a></li>
        <li class="last">Legal</li>
    </ul>
    
    <div id="SitemapSection">

        <h1 id="FirstHeader">Legal Stuff &amp; Acknowledgements</h1>
        
        <h2>Terms &amp; Conditions</h2>
        <p>
            I'm no lawyer, so will keep this simple. But you are free to use all code samples in this website in your own work
            without consent/permission or attribution. Also feel free to use code samples and content in this site as a basis
            for your own blog or website, although if you do so then please attribute me.
        </p>
        
        <h2>Posting Comments</h2>
        <p>
            I encourage you to post comments and am very grateful for any contributions. I won't do a
            <a href="http://www.techdigest.tv/2009/02/facebook_change.html">Facebook</a> and
            try to retain any rights over them, it will be your work. However, any rude, defamatory or racist comments
            will be removed. Also anything considered spam will be removed. It's fine (even encouraged) to post hyperlinks in comments
            (even to plug your own sites) provided that the link is relevent to the content of the blog post or poll in question. Any
            spamy links will be removed.
        </p>
        
        <p>
            If you provide your email address in comments (for auto comment reply notifications), it will be safe and won't be
            given to any third partiy companies. So don't worry about spam.
        </p>
        <p>
            When you post a comment, this site will store your IP address along with the comment in the database. This will be kept safe
            and not given out to anyone. It's purpose to to help to prevent spam, by allowing me to block problematic IP addresses.
        </p>
        
        <h2>Google Analytics</h2>
        <p>
            This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”).
            Google Analytics uses “cookies”, which are text files placed on your computer, to help the website
            analyze how users use the site.
        </p>
        <p>
            The information generated by the cookie about your use of the website (including your IP address)
            will be transmitted to and stored by Google on servers in the United States. Google will use this
            information for the purpose of evaluating your use of the website, compiling reports on website
            activity for website operators and providing other services relating to website activity and internet usage.
        </p>
        <p>
            Google may also transfer this information to third parties where required to do so by law, or where
            such third parties process the information on Google's behalf.
        </p>
        <p>
            Google will not associate your IP address with any other data held by Google.
            You may refuse the use of cookies by selecting the appropriate settings on your browser,
            however please note that if you do this you may not be able to use the full functionality of this website.
        </p>
        <p>
            By using this website, you consent to the processing of data about you by Google in the manner
            and for the purposes set out above.
        </p>

        <h2>Acknowledgements</h2>
        
        <p>
            The HTML/CSS for this site are all completely my own work, however the design of the site is loosely based
            off an open source design from <a href="http://www.infscripts.com/designs/inf08/">Inf Design</a>, many
            thanks for providing it.
        </p>
        
        <p>
            Icons and graphics come from <a href="http://www.famfamfam.com/">FamFamFam's</a> free
            <a href="http://www.famfamfam.com/lab/icons/silk/">Silk Icons set</a>, and <a href="http://www.webappers.com/">Ray Cheung's</a>
            free <a href="http://www.webappers.com/2008/02/12/webappers-released-free-web-application-icons-set/">Web Application Icon set</a>.
            Check out their sites as they provide many free/open license icon sets you can use in your own applications. Many thanks to them.
        </p>
        
    </div>

</asp:Content>
